#!/bin/bash

source /scripts/functions
log_begin_msg
cp -vax /lib64 ${ROOTFS}
for libdir in init lsb terminfo udev; do
  cp -vax /lib/$libdir ${ROOTFS}/lib
done

for usrlibdir in coreutils gcc gnupg locale ${arch}-linux-gnu; do
  cp -vax /usr/lib/$usrlibdir ${ROOTFS}/usr/lib
done

libdir=$(uname -m)-linux-gnu
destlibdir=${ROOTFS}/lib/$libdir
mkdir -p $destlibdir
for lib in acl anl attr audit blkid bz2 c cap cidn com_err \
  crypt cryptsetup dl e2p ext2fs gcc_s gcrypt gpg-error \
  history kmod lzma m memusage mount ncurses ncursesw nsl \
  pcprofile pcre procps pthread readline resolv rt selinux sepol \
  slang ss thread_db tinfo udev usb util uuid z; do
  cp -Pv /lib/${libdir}/lib${lib}.* $destlibdir
  cp -Pv /lib/${libdir}/lib${lib}-* $destlibdir
done
cp -Pv /lib/${libdir}/libnss_* $destlibdir
cp /lib/${libdir}/ld-* $destlibdir

destlibdir=${ROOTFS}/usr/lib/$libdir
mkdir -p $destlibdir
for lib in db form formw menu menuw panel panelw \
  semanage stdc++ tic usb ustr; do
  cp -Pv /usr/lib/${libdir}/lib${lib}.* $destlibdir
  cp -Pv /usr/lib/${libdir}/lib${lib}-* $destlibdir
done
cp -vax /usr/lib/${libdir}/{audit,gconv} $destlibdir

cp -v /lib/klibc-* ${ROOTFS}/lib

log_end_msg
