#!/bin/bash

source /scripts/functions
log_begin_msg

cp -v /bin/live-* ${LIVEROOTFS}/bin
cp -v /boot/vmlinuz-* ${ISODIR}/live
cp -v /boot/initrd.img-* ${ISODIR}/live
cp -vax /lib/modules ${ROOTFS}/lib

# Binaries from klibc-utils
for bin in cat chroot dd dmesg false gunzip gzip ipconfig \
  kill ln ls minips mkdir mount mv reboot sleep \
  sync true umount uname zcat; do
  cp -v /usr/lib/klibc/bin/$bin ${ROOTFS}/bin
done
(cd ${ROOTFS}/bin; ln -sf minips ps)

copy_binary_to_rootfs ${ROOTFS} bash
(cd ${ROOTFS}/bin; ln -sf bash sh)

# Configuration files
for conffile in fstab group gshadow hostname hosts ld.so.cache \
  ld.so.conf localtime nsswitch.conf passwd protocols resolv.conf \
  services shadow shells; do
  cp -v /etc/$conffile ${ROOTFS}/etc
done

for confdir in ld.so.conf.d network selinux security udev; do
  cp -vax /etc/$confdir ${ROOTFS}/etc
done

# For debugging
copy_binary_to_rootfs ${ROOTFS} ifconfig ping vi
copy_binary_to_rootfs ${ROOTFS} more mke2fs cfdisk ldd

log_end_msg
