#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSROOTDIR}; mkdir -p $destdir
cp -v /scripts/init.sh $destdir

for dir in bin dev etc lib proc root run sbin sys tmp usr \
  usr/lib usr/bin usr/sbin usr/share var var/run var/log var/lib; do
  mkdir -p ${destdir}/$dir
done

cp -vax /lib64 ${destdir}
cp -v /lib/klibc-* ${destdir}/lib
cp -vax /lib/{firmware,init,lsb,modules,terminfo,xtables} ${destdir}/lib

libdir=$(uname -m)-linux-gnu
destlibdir=${destdir}/lib/$libdir; mkdir -p $destlibdir
cp -v /lib/${libdir}/libnsl-* $destlibdir
cp -Pv /lib/${libdir}/libnsl.* $destlibdir
cp -Pv /lib/${libdir}/libnss_* $destlibdir
cp -v /lib/${libdir}/libresolv-* $destlibdir
cp -Pv /lib/${libdir}/libresolv.* $destlibdir
cp -v /lib/${libdir}/ld-* $destlibdir

# Binaries from klibc-utils
for bin in cat dmesg false gunzip gzip ipconfig \
  kill ln mv reboot sleep \
  sync true uname zcat; do
  cp -v /usr/lib/klibc/bin/$bin ${destdir}/bin
done

cp -v /bin/live-* ${destdir}/bin
copy_binary_to_rootfs ${destdir} \
  auplink \
  awk \
  basename \
  bash \
  brctl \
  bridge \
  chgrp \
  clear \
  cp \
  date \
  dd \
  docker \
  echo \
  egrep \
  env \
  find \
  grep \
  head \
  hwclock \
  id \
  ifconfig \
  insmod \
  ip \
  ip6tables \
  ip6tables-save \
  iptables \
  iptables-save \
  ls \
  lsmod \
  mkdir \
  modprobe \
  mount \
  mountpoint \
  ping \
  printf \
  ps \
  rm \
  rmdir \
  sed \
  start-stop-daemon \
  sysctl \
  tail \
  test \
  touch \
  ulimit \
  umount

(cd ${destdir}/bin; ln -sf bash sh)
(cd ${destdir}; ln -sf /usr/bin/touch bin)

# Configuration files
printf 'DOCKER_OPTS="-s aufs --host tcp://0.0.0.0:2375 \
  --host unix:///var/run/docker.sock"\n' >> /etc/default/docker
groupadd docker

for conffile in fstab group gshadow hostname \
  hosts ld.so.cache ld.so.conf localtime nsswitch.conf passwd protocols \
  resolv.conf services shadow shells sysctl.conf; do
  cp -v /etc/$conffile ${destdir}/etc
done

for confdir in default init.d iproute2 ld.so.conf.d \
  network selinux security ssl sysctl.d; do
  cp -vax /etc/$confdir ${destdir}/etc
done

echo $DISTVER > ${destdir}/etc/version
echo $PUBLISHER > ${destdir}/etc/publisher

log_end_msg
