#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSROOTDIR}; mkdir -p $destdir

# Root filesystem hierarchy
for dir in \
  bin \
  dev \
  etc \
  lib \
  lib/ddcos \
  media \
  proc \
  root \
  run \
  sbin \
  sys \
  tmp \
  usr \
  usr/bin \
  usr/lib \
  usr/sbin \
  var \
  var/run \
  var/log \
  var/lib \
; do
  mkdir -p ${destdir}/$dir
done

# System libraries
for lib in \
  /lib64 \
  /lib/klibc-* \
  /lib/firmware \
  /lib/ifupdown \
  /lib/init \
  /lib/lsb \
  /lib/modules \
  /lib/startpar \
  /lib/systemd \
  /lib/sysvinit \
  /lib/terminfo \
  /lib/udev \
  /lib/$(uname -m)-linux-gnu \
  /lib/xtables \
  /usr/lib/binfmt.d \
  /usr/lib/sysctl.d \
  /usr/lib/systemd \
  /usr/lib/tmpfiles.d \
; do
  cp -vax $lib ${destdir}$(dirname $lib)
done
cp -v /lib/ddcos/init.sh $destdir/lib/ddcos

# System binaries
ln -sf /bin/bash ${destdir}/bin/sh
ln -sf /bin/systemctl ${destdir}/sbin/telinit
ln -sf /lib/systemd/systemd ${destdir}/bin
ln -sf /lib/systemd/systemd ${destdir}/sbin/init
ln -sf /lib/systemd/systemd-bus-proxyd ${destdir}/usr/bin/systemd-stdio-bridge
ln -sf /lib/systemd/systemd-udevd ${destdir}/sbin/udevd
ln -sf /usr/bin/touch ${destdir}/bin

copy_binary_to_rootfs ${destdir} \
  agetty \
  auplink \
  awk \
  basename \
  bash \
  chgrp \
  clear \
  cp \
  dd \
  docker \
  echo \
  egrep \
  find \
  git \
  grep \
  head \
  id \
  ifdown \
  ifquery \
  ifup \
  insserv \
  ip \
  ip6tables \
  ip6tables-save \
  iptables \
  iptables-save \
  kmod \
  login \
  ls \
  mkdir \
  modprobe \
  mount \
  mountpoint \
  printf \
  ps \
  pump \
  readlink \
  rm \
  rmdir \
  run-parts \
  sed \
  start-stop-daemon \
  sysctl \
  systemctl \
  systemd-ask-password \
  systemd-analyze \
  systemd-cat \
  systemd-cgls \
  systemd-cgtop \
  systemd-delta \
  systemd-detect-virt \
  systemd-escape \
  systemd-inhibit \
  systemd-machine-id-setup \
  systemd-nspawn \
  systemd-notify \
  systemd-path \
  systemd-run \
  systemd-tmpfiles \
  systemd-tty-ask-password-agent \
  tail \
  test \
  touch \
  udevadm \
  ulimit \
  umask \
  umount \
  xz

# Binaries from klibc-utils
for bin in \
  cat \
  dmesg \
  false \
  gunzip \
  gzip \
  ipconfig \
  kill \
  ln \
  mv \
  reboot \
  sleep \
  sync \
  true \
  uname \
  zcat \
; do
  cp -v /usr/lib/klibc/bin/$bin ${destdir}/bin
done

# Configuration files
printf 'DOCKER_OPTS=" \
  -s aufs \
  --host tcp://0.0.0.0:2375 \
  --host unix:///var/run/docker.sock \
"\n' >> /etc/default/docker

for conf in \
  default \
  fstab \
  group \
  gshadow \
  hostname \
  hosts \
  init \
  init.d \
  insserv \
  insserv.conf \
  insserv.conf.d \
  ld.so.cache \
  ld.so.conf \
  ld.so.conf.d \
  localtime \
  login.defs \
  network \
  nsswitch.conf \
  pam.conf \
  pam.d \
  passwd \
  protocols \
  rc?.d \
  resolv.conf \
  securetty \
  security \
  selinux \
  services \
  shadow \
  shells \
  ssl \
  sysctl.conf \
  sysctl.d \
  systemd \
  udev \
; do
  cp -vax /etc/$conf ${destdir}/etc
done

touch ${destdir}/etc/resolv.conf
echo $DISTVER > ${destdir}/etc/version
echo $PUBLISHER > ${destdir}/etc/publisher

log_end_msg
