#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSDIR}/utils
mkdir -p $destdir
copy_binary_to_rootfs ${destdir} \
  cfdisk \
  more \
  ldd \
  lsmod \
  ping \
  strace \
  vi

log_end_msg
