#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSDIR}/install
mkdir -p $destdir
cp -v /scripts/install.sh $destdir

copy_binary_to_rootfs $destdir \
  extlinux \
  fdisk \
  lsblk \
  mke2fs \
  udevadm \
  whiptail

(cd ${destdir}/sbin; ln -sf mke2fs mkfs.ext4)

mkdir -p ${destdir}/usr/lib/syslinux/modules
cp -vax /usr/lib/syslinux/modules/bios ${destdir}/usr/lib/syslinux/modules
cp -vax /usr/lib/syslinux/mbr ${destdir}/usr/lib/syslinux

log_end_msg
