#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSDIR}/install

mkdir -p $destdir/lib/ddcos
cp -v /lib/ddcos/install.sh $destdir/lib/ddcos

copy_binary_to_rootfs $destdir \
  extlinux \
  fdisk \
  lsblk \
  mke2fs \
  whiptail

(cd ${destdir}/sbin; ln -sf mke2fs mkfs.ext4)

mkdir -p ${destdir}/usr/lib/syslinux/modules
cp -vax /usr/lib/syslinux/modules/bios ${destdir}/usr/lib/syslinux/modules
cp -vax /usr/lib/syslinux/mbr ${destdir}/usr/lib/syslinux

log_end_msg
