#!/bin/bash

source ./functions
log_begin_msg

destdir=${SQUASHFSDIR}/docker
mkdir -p $destdir

copy_binary_to_rootfs $destdir iptables docker

mkdir -p ${destdir}/lib
cp -vax /lib/xtables ${destdir}/lib

log_end_msg
