#!/bin/bash

source /scripts/functions
log_begin_msg

rm -rf ${INSTALLROOTFS}
cp -ax ${ROOTFS} ${INSTALLROOTFS}
cp -v /scripts/install.sh ${INSTALLROOTFS}/init.sh

copy_binary_to_rootfs ${INSTALLROOTFS} whiptail awk lsblk udevadm grep fdisk

log_end_msg
