#!/bin/bash

source ./functions
log_begin_msg

cp -v /boot/vmlinuz-* ${ISODIR}/live
cp -v /boot/initrd.img-* ${ISODIR}/live

vmlinuz=$(basename ${ISODIR}/live/vmlinuz-*)
initrd=$(basename ${ISODIR}/live/initrd.img-*)

cp -vax /tmp/isolinux ${ISODIR}
sed -i  -e "s/@KERNEL@/${vmlinuz}/" \
        -e "s/@INITRD@/${initrd}/" \
	-e "s#@KERNEL_BOOT_PARAMS@#${KERNEL_BOOT_PARAMS}#" \
        ${ISODIR}/isolinux/isolinux.cfg

cp -v ${SQUASHFSDIR}/*.squashfs ${ISODIR}/live
echo $KERNEL_BOOT_PARAMS > ${ISODIR}/live/bootparams.txt

log_end_msg
