#!/bin/bash

source ./functions
log_begin_msg

xorriso -publisher "${PUBLISHER}"                               \
        -as mkisofs -l -J -R                                    \
        -V "${DISTVER}"                                         \
        -no-emul-boot -boot-load-size 4 -boot-info-table        \
        -b isolinux/isolinux.bin                                \
        -c isolinux/boot.cat                                    \
        -isohybrid-mbr ${ISODIR}/isolinux/isohdpfx.bin          \
        -o $ISOFILE $ISODIR

log_end_msg
