#!/bin/bash

source /scripts/functions

copy_binary_to_rootfs()
{
  local _rootdir _locbin _destdir
  _rootdir=${1}; shift
  for bin in $@; do
    _locbin=$(whereis $bin | cut -f2 -d' ')
    [ -e "$_locbin" ] || continue
    _destdir=${_rootdir}$(dirname $_locbin)
    [ -d $_destdir ] || mkdir -p $_destdir
    cp -vL $_locbin $_destdir/$bin
    for lib in $(ldd $_locbin | awk '/=> /{print $3}'); do
      [ -e ${SQUASHFSROOTDIR}${lib} ] && continue
      _destdir=${SQUASHFSROOTDIR}$(dirname $lib)
      [ -d $_destdir ] || mkdir -p $_destdir
      # we don't care about lib symlinks here.
      cp -v $lib $_destdir
    done
  done
}
