#!/bin/bash

DISTVER="${DISTNAME}-${VERSION}"
BUILDPKGS="dpkg-dev"
PKGS="\
  whiptail \
  squashfs-tools \
  xorriso \
\
  restartd \
  lxc-docker \
  apparmor \
  iptables \
  live-boot \
  linux-image-amd64 \
  firmware-linux-free \
  mdadm \
\
  net-tools \
  vim-tiny \
"
export DISTVER BUILDPKGS PKGS

APTDIR="/archives"
PKGDIR="/archives/dists/local/main/binary-amd64"
export APTDIR PKGDIR
