#!/bin/bash

DISTVER="${DISTNAME}-${VERSION}"
BUILDPKGS="dpkg-dev"
RUNPKGS="squashfs-tools xorriso"
BOOTPKGS="live-boot linux-image-amd64 firmware-linux-free mdadm"
BASEPKGS="\
  restartd \
  lxc-docker \
  apparmor \
  iptables \
  live-boot \
\
  net-tools \
  vim-tiny \
"
export DISTVER BUILDPKGS RUNPKGS BOOTPKGS BASEPKGS

APTDIR="/archives"
PKGDIR="/archives/dists/local/main/binary-amd64"
export APTDIR PKGDIR
