#!/bin/bash

DISTVER="${DISTNAME}-${VERSION}"
BUILDPKGS="dpkg-dev"
PKGS="\
  whiptail \
  squashfs-tools \
  xorriso \
  extlinux \
  syslinux-common \
\
  ca-certificates \
  lxc-docker \
  aufs-tools \
  ifupdown \
  pump \
  iptables \
  live-boot \
  linux-image-amd64 \
  firmware-linux-free \
  firmware-realtek \
  mdadm \
  net-tools \
  xz-utils \
  git \
  sysvinit \
"
export DISTVER BUILDPKGS PKGS

APTDIR="/archives"
PKGDIR="/archives/dists/local/main/binary-amd64"
export APTDIR PKGDIR

KERNEL_BOOT_PARAMS="quiet splash persistence cgroup_enable=memory swapaccount=1 init=/lib/ddcos/init.sh"
export KERNEL_BOOT_PARAMS
