#!/bin/bash

abort()
{
  echo "!!! Aborted"
  printf "\n\n%s: %s\n\n" "Reason" "$@"
  exit 1
}

log_begin_msg()
{
  echo " ---> Running $0"
}

log_end_msg()
{
  echo " <--- Exiting $0"; exit 0
}

run_scripts()
{
	rundir=/scripts/$1
	[ -d $rundir ] || return
	scripts=($(echo ${rundir}/* | sed "s@${rundir}/config@@"))
	(. ${rundir}/config && for script in "${scripts[@]}"; do
		$script; ec=$?
		if [ "$ec" -ne 0 ]; then
			PS1="($1) " /bin/bash --norc
			echo "E: $script failed with return $ec."
			exit $ec
		fi
	done)
}

copy_binary_to_rootfs()
{
  local _rootdir _locbin _destdir
  _rootdir=${1}; shift
  for bin in $@; do
    _locbin=$(whereis $bin | cut -f2 -d' ')
    [ -e "$_locbin" ] || continue
    _destdir=${_rootdir}$(dirname $_locbin)
    [ -d $_destdir ] || mkdir -p $_destdir
    cp -vL $_locbin $_destdir/$bin
    for lib in $(ldd $_locbin | awk '/=> /{print $3}'); do
      for dir in ${SQUASHFSDIR}/*/; do
        [ -e ${dir%%/}${lib} ] && continue 2
      done
      [ -e ${_rootdir}${lib} ] && continue
      _destdir=${_rootdir}$(dirname $lib)
      [ -d $_destdir ] || mkdir -p $_destdir
      # we don't care about lib symlinks here.
      cp -v $lib $_destdir
    done
  done
}
