#!/bin/bash

abort()
{
  echo "!!! Aborted"
  printf "\n\n%s: %s\n\n" "Reason" "$@"
  exit 1
}

log_begin_msg()
{
  echo " ---> Running $0"
}

log_end_msg()
{
  echo " <--- Exiting $0"; exit 0
}

run_scripts()
{
	rundir=/scripts/$1
	[ -d $rundir ] || return
	scripts=($(echo ${rundir}/* | sed "s@${rundir}/config@@"))
	(. ${rundir}/config && for script in "${scripts[@]}"; do
		$script; ec=$?
		if [ "$ec" -ne 0 ]; then
			PS1="($1) " /bin/bash --norc
			echo "E: $script failed with return $ec."
			exit $ec
		fi
	done)
}

copy_binary_to_rootfs()
{
  rootdir=${1}; shift
  for bin in $@; do
    locbin=$(whereis $bin | cut -f2 -d' ')
    destdir=${rootdir}$(dirname $locbin)
    [ -d $destdir ] || mkdir -p $destdir
    cp -v $locbin $destdir
    for lib in $(ldd $locbin | awk '/=> /{print $3}'); do
      [ -e ${rootdir}${lib} ] && continue
      destdir=${rootdir}$(dirname $lib)
      [ -d $destdir ] || mkdir -p $destdir
      # we don't care about lib symlinks here.
      cp -v $lib $destdir
    done
  done
}
